import Lean
import OverloadTest.Ledger

/-!
# Coverage report

`#coverage_report Overload` classifies every declaration under the namespace
by verification class and fails elaboration if any is uncovered. The classes,
strongest first:

* **C4 bridged** — named in `bridgedLedger`: proved equivalent to an
  independent formulation.
* **C3 pinned** — a concrete regression (a theorem whose statement quantifies
  over nothing — see `isConcreteStatement`), or in the transitive dependency
  cone of one: the kernel checked a closed fact through it.
* **C2 witnessed** — declared in a witness module (`Overload.Witnesses`,
  `Overload.Examples.*` — the regression layer itself), or in the transitive
  dependency cone of one: a concrete, kernel-checked instance exercises it.
* **C1 consumed** — some other declaration's type or proof uses it, computed
  from `Expr.getUsedConstants` over the kernel terms, so dot-notation and
  every other surface spelling are invisible to it.
* **T terminal** — consumed by nothing, ledgered in `terminalLedger` with a
  justification.
* **C0 uncovered** — none of the above. **The report throws**, listing them.

Auto-generated names (equation lemmas, `casesOn`-family, constructors,
`match_`/`proof_` auxiliaries, derived instances) are exempt from the
universe but remain edges: a proof that consumes `f.eq_1` consumes `f`.
The exempt count is printed so the universe's reach is visible.

Consumption is counted from every constant compiled in a module of the target
package (internal auxiliaries included — a theorem's `_proof_1` consuming a
lemma is the theorem consuming it), except that a constant never covers a
declaration that is a prefix of its own name: `f.eq_1` using `f` is not
evidence anyone needs `f`.
-/

namespace OverloadTest

open Lean

/-- Compiler-generated companions of a hand-written declaration. They are
exempt from the coverage universe (nobody owes them a witness) but stay in
the graph as edges. `inst`-prefixed names are exempt because this library
declares zero instances by hand — derived `SizeOf`/`Repr` instances are the
only ones that exist. -/
def isAutoGenerated : Name → Bool
  | .str _ s =>
    s == "casesOn" || s == "recOn" || s == "brecOn" || s == "binductionOn"
      || s == "rec" || s == "below" || s == "ibelow" || s == "ndrec"
      || s == "noConfusion" || s == "noConfusionType" || s == "injEq"
      || s == "sizeOf_spec" || s == "eq_def" || s == "mk" || s == "ctorIdx"
      -- Compiler equation/match/proof auxiliaries carry numeric suffixes
      -- (`eq_1`, `match_1_1`, `proof_2`); a bare prefix test also swallows
      -- hand-written names — `ClosedLoop.eq_ge_of_over` was silently outside
      -- the universe, the manifest, and the lock until the digit test below
      -- (same defect class as the `instrument_blind` swallow).
      || (s.startsWith "eq_" && (s.drop 3).front.isDigit)
      || (s.startsWith "match_" && (s.drop 6).front.isDigit)
      || (s.startsWith "proof_" && (s.drop 6).front.isDigit)
      || s == "congr" || s == "congr_simp" || s == "congr_arg"
      || (s.startsWith "congr_" && (s.drop 6).front.isDigit)
      -- Derived instances are `inst` + UpperCamelCase; the case test keeps
      -- hand-written names like `instrument_blind` in the universe (that one
      -- was silently swallowed by a bare-prefix test — real defect).
      || (s.startsWith "inst" && ((s.drop 4).front.isUpper))
      || (s.startsWith "sizeOf" && s != "sizeOf")
  | _ => false

/-- A concrete statement: the top-level `∀`-telescope binds nothing the rest
of the statement mentions, so the claim is about closed terms — a numeric
regression or a concrete counterexample. Such a theorem is its own test (the
kernel checked a closed fact), and everything in its dependency cone is
pinned by it. Quantifiers inside definitions the statement applies
(`BistableOn` unfolds to one) do not count: the statement as stated names
concrete objects. -/
def isConcreteStatement : Lean.Expr → Bool
  | .forallE _ _ body _ => !body.hasLooseBVar 0 && isConcreteStatement body
  | _ => true

/-- The module name a declaration was compiled in, if it came from an import. -/
def moduleOf? (env : Environment) (n : Name) : Option Name := do
  let idx ← env.getModuleIdxFor? n
  env.header.moduleNames[idx.toNat]?

/-- Whether `mod` is a witness module: the regression layer whose concrete
instances are the tests. -/
def isWitnessModule (root : Name) : Name → Bool
  | mod =>
    mod == root ++ `Witnesses || (root ++ `Examples).isPrefixOf mod

end OverloadTest

open Lean Elab Command in
/-- `#coverage_report Overload` fails elaboration unless every non-exempt
declaration under the namespace is bridged, witnessed, consumed, or ledgered
terminal. Prints the class tally so coverage is a build-log fact. See the
module docstring for the classes and the ledgers in `OverloadTest.Ledger`. -/
elab "#coverage_report " pfx:ident : command => do
  let env ← getEnv
  let root := pfx.getId
  let inPackage (n : Name) : Bool :=
    match OverloadTest.moduleOf? env n with
    | some mod => mod.getRoot == root
    | none => true  -- compiled in the current file
  -- The universe: hand-written declarations under the namespace.
  let mut univ : NameSet := {}
  let mut exempt : Nat := 0
  for (n, _) in env.constants.toList do
    if n.getRoot == root && !n.isInternal then
      -- Projections are exempt with the other compiler output: a field is
      -- covered by any witness that constructs the structure, and the
      -- projection function itself is machinery.
      if OverloadTest.isAutoGenerated n || env.isProjectionFn n then
        exempt := exempt + 1
      else univ := univ.insert n
  if univ.isEmpty then
    throwError "#coverage_report: no declarations found under `{root}`"
  -- Dependencies of a constant, restricted to the universe, expanding
  -- through non-universe names under the root (auto-generated companions,
  -- internal auxiliaries) so `f.eq_1` and `_proof_1` links are not lost.
  let expandedDeps (start : Name) : NameSet := Id.run do
    let mut seen : NameSet := {}
    let mut deps : NameSet := {}
    let mut work : List Name := [start]
    while h : work ≠ [] do
      let n := work.head h
      work := work.tail
      if seen.contains n then continue
      seen := seen.insert n
      let some ci := env.find? n | continue
      for d in ci.getUsedConstantsAsSet do
        if d.getRoot == root && d != start then
          if univ.contains d then deps := deps.insert d
          else work := d :: work
    return deps
  -- Consumers: every constant compiled in this package, internal included,
  -- credits its universe dependencies — except along its own name prefix.
  let mut consumed : NameSet := {}
  let mut depsOf : NameMap NameSet := {}
  for (n, _) in env.constants.toList do
    if inPackage n then
      let deps := expandedDeps n
      if univ.contains n then depsOf := depsOf.insert n deps
      for d in deps do
        unless d.isPrefixOf n do consumed := consumed.insert d
  -- Cone closure from a root set over the dependency edges.
  let cone (roots : List Name) : NameSet := Id.run do
    let mut seen : NameSet := {}
    let mut work := roots
    while h : work ≠ [] do
      let n := work.head h
      work := work.tail
      if seen.contains n then continue
      seen := seen.insert n
      for d in (depsOf.find? n).getD (expandedDeps n) do
        if !seen.contains d then work := d :: work
    return seen
  -- Pinned: concrete regressions (closed statements) plus their cones.
  let mut pinRoots : List Name := []
  for n in univ do
    if let some (.thmInfo t) := env.find? n then
      if OverloadTest.isConcreteStatement t.type then pinRoots := n :: pinRoots
  let pinned := cone pinRoots
  -- Witnessed: members of witness modules plus their cones.
  let mut witnessRoots : List Name := []
  for n in univ do
    match OverloadTest.moduleOf? env n with
    | some mod =>
      if OverloadTest.isWitnessModule root mod then witnessRoots := n :: witnessRoots
    | none => pure ()
  let witnessed := cone witnessRoots
  -- Ledgers, with staleness checks.
  -- Ledger entries for other namespaces are ignored: the ledgers are global,
  -- the report is per-root (the fixture reports over its own tiny namespace).
  let mut bridged : NameSet := {}
  for (target, bridge) in OverloadTest.bridgedLedger do
    unless target.getRoot == root do continue
    unless univ.contains target do
      throwError "#coverage_report: bridged ledger names `{target}`, which is not in the universe"
    let some _ := env.find? bridge
      | throwError "#coverage_report: bridged ledger cites missing bridge `{bridge}`"
    unless (expandedDeps bridge).contains target do
      throwError "#coverage_report: `{bridge}` does not depend on `{target}`; the bridge entry is stale"
    bridged := bridged.insert target
    if univ.contains bridge then bridged := bridged.insert bridge
  let mut terminal : NameSet := {}
  for (n, why) in OverloadTest.terminalLedger do
    unless n.getRoot == root do continue
    unless univ.contains n do
      throwError "#coverage_report: terminal ledger names `{n}`, which is not in the universe"
    if consumed.contains n || witnessed.contains n || pinned.contains n then
      throwError "#coverage_report: terminal entry `{n}` ({why}) is now covered — delete the entry"
    terminal := terminal.insert n
  -- Tally, strongest class first.
  let mut c4 := 0; let mut c3 := 0; let mut c2 := 0; let mut c1 := 0; let mut t := 0
  let mut uncovered : Array Name := #[]
  for n in univ do
    if bridged.contains n then c4 := c4 + 1
    else if pinned.contains n then c3 := c3 + 1
    else if witnessed.contains n then c2 := c2 + 1
    else if consumed.contains n then c1 := c1 + 1
    else if terminal.contains n then t := t + 1
    else uncovered := uncovered.push n
  let total := univ.size
  let pct (k : Nat) : Nat := k * 100 / total
  unless uncovered.isEmpty do
    let names := uncovered.qsort (·.toString < ·.toString)
    throwError "#coverage_report: {uncovered.size} uncovered (C0) declaration(s) under `{root}`:{indentD (MessageData.joinSep (names.toList.map (m!"{·}")) Format.line)}"
  logInfo m!"#coverage_report: {total} declarations under `{root}` — \
    C4 bridged {c4} ({pct c4}%), C3 pinned {c3} ({pct c3}%), \
    C2 witnessed {c2} ({pct c2}%), C1 consumed {c1} ({pct c1}%), \
    terminal {t} ({pct t}%), C0 uncovered 0 \
    (exempt auto-generated: {exempt})"
