module

public import Lean
public import OverloadTest.Ledger

/-!
# Coverage report

`#coverage_report Overload` (defined in `OverloadTest/Gate.lean`, from the
helpers and ledgers here) classifies every declaration under the namespace
by verification class and fails elaboration if any is uncovered. The classes,
strongest first:

* **C4 bridged** — named in `bridgedLedger`: proved equivalent to an
  independent formulation.
* **C3 pinned** — a concrete regression (a theorem whose statement quantifies
  over nothing — see `isConcreteStatement`), or in the transitive dependency
  cone of one: the kernel checked a closed fact through it.
* **C2 witnessed** — declared in a witness module
  (`Overload.Verification.Witnesses`, `Overload.Examples.*` — the regression
  layer itself), or in the transitive
  dependency cone of one: a concrete, kernel-checked instance exercises it.
* **C1 consumed** — some other declaration's type or proof uses it, computed
  from `Expr.getUsedConstants` over the kernel terms, so dot-notation and
  every other surface spelling are invisible to it.
* **T terminal** — consumed by nothing, ledgered in `terminalLedger` with a
  justification.
* **C0 uncovered** — none of the above. **The report throws**, listing them.

Auto-generated names (equation lemmas, `casesOn`-family, constructors,
`match_`/`proof_` auxiliaries, derived instances) are exempt from the
universe but remain edges: a proof that consumes `f.eq_1` consumes `f`.
The exempt count is printed so the universe's reach is visible.

Consumption is counted from every constant compiled in a module of the target
package (internal auxiliaries included — a theorem's `_proof_1` consuming a
lemma is the theorem consuming it), except that a constant never covers a
declaration that is a prefix of its own name: `f.eq_1` using `f` is not
evidence anyone needs `f`.
-/

@[expose] public section

namespace OverloadTest

open Lean

/-- The audited-namespace rule: a copy of `inAuditedNamespace`'s two lines
from `Overload/AxiomAudit.lean`, under a different name because the fixture
docstrings cite that one.

Copied rather than shared because that one lives in a `meta section` — the
audit commands reading it are elaborators — and the module system forbids a
plain `def` from referencing a `meta` one, in either direction. This copy is
the non-`meta` home: `#coverage_report` reaches it through Gate.lean's
`meta import`, and the test driver calls it at runtime.

Keep the two identical. They were not, on 2026-07-29: this side still used
`n.getRoot == root && !n.isInternal`, which skips a mangled
`_private.<Module>.<n>.<Name>`, so the driver printed 914 where the build
printed 919 for the same stated quantity, and every gate stayed green. Two
totals that are never compared are two unchecked numbers. -/
def auditRule (root n : Name) : Bool :=
  let u := privateToUserName n
  u.getRoot == root && !u.isInternal

/-- Compiler-generated companions of a hand-written declaration. They are
exempt from the coverage universe (nobody owes them a witness) but stay in
the graph as edges. `inst`-prefixed names are exempt because this library
declares zero instances by hand — derived `SizeOf`/`Repr` instances are the
only ones that exist. -/
def isAutoGenerated : Name → Bool
  | .str _ s =>
    s == "casesOn" || s == "recOn" || s == "brecOn" || s == "binductionOn"
      || s == "rec" || s == "below" || s == "ibelow" || s == "ndrec"
      || s == "noConfusion" || s == "noConfusionType" || s == "injEq"
      || s == "sizeOf_spec" || s == "eq_def" || s == "mk" || s == "ctorIdx"
      -- Compiler equation/match/proof auxiliaries carry numeric suffixes
      -- (`eq_1`, `match_1_1`, `proof_2`); a bare prefix test also swallows
      -- hand-written names — `ClosedLoop.eq_ge_of_over` was silently outside
      -- the universe, the manifest, and the lock until the digit test below
      -- (same defect class as the `instrument_blind` swallow).
      || (s.startsWith "eq_" && (s.drop 3).front.isDigit)
      || (s.startsWith "match_" && (s.drop 6).front.isDigit)
      || (s.startsWith "proof_" && (s.drop 6).front.isDigit)
      || s == "congr" || s == "congr_simp" || s == "congr_arg"
      || (s.startsWith "congr_" && (s.drop 6).front.isDigit)
      -- Derived instances are `inst` + UpperCamelCase; the case test keeps
      -- hand-written names like `instrument_blind` in the universe (that one
      -- was silently swallowed by a bare-prefix test — real defect).
      || (s.startsWith "inst" && ((s.drop 4).front.isUpper))
      || (s.startsWith "sizeOf" && s != "sizeOf")
  | _ => false

/-- A concrete statement: the top-level `∀`-telescope binds nothing the rest
of the statement mentions, so the claim is about closed terms — a numeric
regression or a concrete counterexample. Such a theorem is its own test (the
kernel checked a closed fact), and everything in its dependency cone is
pinned by it. Quantifiers inside definitions the statement applies
(`BistableOn` unfolds to one) do not count: the statement as stated names
concrete objects. -/
def isConcreteStatement : Lean.Expr → Bool
  | .forallE _ _ body _ => !body.hasLooseBVar 0 && isConcreteStatement body
  | _ => true

/-- The module name a declaration was compiled in, if it came from an import. -/
def moduleOf? (env : Environment) (n : Name) : Option Name := do
  let idx ← env.getModuleIdxFor? n
  env.header.moduleNames[idx.toNat]?

/-- Whether `mod` is a witness module: the regression layer whose concrete
instances are the tests. -/
def isWitnessModule (root : Name) : Name → Bool
  | mod =>
    mod == root ++ `Verification.Witnesses || (root ++ `Examples).isPrefixOf mod

end OverloadTest
