module

public import Lean
public import OverloadTest.Ledger

/-!
# Coverage report

The coverage graph and classification live here as plain functions over
`Environment`, so both phases read one code path: `#coverage_report`
(`OverloadTest/Gate.lean`, reached through that file's `meta import`)
classifies every declaration under the namespace at build time and fails
elaboration if any is uncovered, and the test driver
(`OverloadTest/Main.lean`) calls the same functions at runtime to stamp
each manifest row's class. The classes, strongest first:

* **C4 bridged** — named in `bridgedLedger`: proved equivalent to an
  independent formulation.
* **C3 pinned** — a concrete regression (a theorem whose statement quantifies
  over nothing — see `isConcreteStatement`), or in the transitive dependency
  cone of one: the kernel checked a closed fact through it.
* **C2 witnessed** — declared in a witness module
  (`Overload.Verification.Witnesses`, `Overload.Examples.*` — the regression
  layer itself), or in the transitive
  dependency cone of one: a concrete, kernel-checked instance exercises it.
* **C1 consumed** — some other declaration's type or proof uses it, computed
  from `Expr.getUsedConstants` over the kernel terms, so dot-notation and
  every other surface spelling are invisible to it.
* **T terminal** — consumed by nothing, ledgered in `terminalLedger` with a
  justification.
* **C0 uncovered** — none of the above. **The report throws**, listing them.

Auto-generated names (equation lemmas, `casesOn`-family, constructors,
`match_`/`proof_` auxiliaries, derived instances) are exempt from the
universe but remain edges: a proof that consumes `f.eq_1` consumes `f`.
The exempt count is printed so the universe's reach is visible.

Consumption is counted from every constant compiled in a module of the target
package (internal auxiliaries included — a theorem's `_proof_1` consuming a
lemma is the theorem consuming it), except that a constant never covers a
declaration that is a prefix of its own name: `f.eq_1` using `f` is not
evidence anyone needs `f`.
-/

@[expose] public section

namespace OverloadTest

open Lean

/-- The audited-namespace rule: a copy of `inAuditedNamespace`'s two lines
from `Overload/AxiomAudit.lean`, under a different name because the fixture
docstrings cite that one.

Copied rather than shared because that one lives in a `meta section` — the
audit commands reading it are elaborators — and the module system forbids a
plain `def` from referencing a `meta` one, in either direction. This copy is
the non-`meta` home: `#coverage_report` reaches it through Gate.lean's
`meta import`, and the test driver calls it at runtime.

Keep the two identical. They were not, on 2026-07-29: this side still used
`n.getRoot == root && !n.isInternal`, which skips a mangled
`_private.<Module>.<n>.<Name>`, so the driver printed 914 where the build
printed 919 for the same stated quantity, and every gate stayed green. Two
totals that are never compared are two unchecked numbers. -/
def auditRule (root n : Name) : Bool :=
  let u := privateToUserName n
  u.getRoot == root && !u.isInternal

/-- Compiler-generated companions of a hand-written declaration. They are
exempt from the coverage universe (nobody owes them a witness) but stay in
the graph as edges. `inst`-prefixed names are exempt because this library
declares zero instances by hand — derived `SizeOf`/`Repr` instances are the
only ones that exist. -/
def isAutoGenerated : Name → Bool
  | .str _ s =>
    s == "casesOn" || s == "recOn" || s == "brecOn" || s == "binductionOn"
      || s == "rec" || s == "below" || s == "ibelow" || s == "ndrec"
      || s == "noConfusion" || s == "noConfusionType" || s == "injEq"
      -- `inj` is `injEq`'s sibling; a compiler suffix missing from this list
      -- is the converse swallow — eight `mk.inj` theorems sat in the lock as
      -- if hand-written. Exact match, and no hand-written name here is `inj`.
      || s == "inj"
      || s == "sizeOf_spec" || s == "eq_def" || s == "mk" || s == "ctorIdx"
      -- Compiler equation/match/proof auxiliaries carry numeric suffixes
      -- (`eq_1`, `match_1_1`, `proof_2`); a bare prefix test also swallows
      -- hand-written names — `ClosedLoop.eq_ge_of_over` was silently outside
      -- the universe, the manifest, and the lock until the digit test below
      -- (same defect class as the `instrument_blind` swallow).
      || (s.startsWith "eq_" && (s.drop 3).front.isDigit)
      || (s.startsWith "match_" && (s.drop 6).front.isDigit)
      || (s.startsWith "proof_" && (s.drop 6).front.isDigit)
      || s == "congr" || s == "congr_simp" || s == "congr_arg"
      || (s.startsWith "congr_" && (s.drop 6).front.isDigit)
      -- Derived instances are `inst` + UpperCamelCase; the case test keeps
      -- hand-written names like `instrument_blind` in the universe (that one
      -- was silently swallowed by a bare-prefix test — real defect).
      || (s.startsWith "inst" && ((s.drop 4).front.isUpper))
      || (s.startsWith "sizeOf" && s != "sizeOf")
  | _ => false

/-- A concrete statement: the top-level `∀`-telescope binds nothing the rest
of the statement mentions, so the claim is about closed terms — a numeric
regression or a concrete counterexample. Such a theorem is its own test (the
kernel checked a closed fact), and everything in its dependency cone is
pinned by it. Quantifiers inside definitions the statement applies
(`BistableOn` unfolds to one) do not count: the statement as stated names
concrete objects. -/
def isConcreteStatement : Lean.Expr → Bool
  | .forallE _ _ body _ => !body.hasLooseBVar 0 && isConcreteStatement body
  | _ => true

/-- The module name a declaration was compiled in, if it came from an import. -/
def moduleOf? (env : Environment) (n : Name) : Option Name := do
  let idx ← env.getModuleIdxFor? n
  env.header.moduleNames[idx.toNat]?

/-- Whether `mod` is a witness module: the regression layer whose concrete
instances are the tests. -/
def isWitnessModule (root : Name) : Name → Bool
  | mod =>
    mod == root ++ `Verification.Witnesses || (root ++ `Examples).isPrefixOf mod

/-- Verification class of one declaration, strongest first; see the module
docstring for what each class asserts. -/
inductive CovClass
  /-- Bridged: named in `bridgedLedger`. -/
  | c4
  /-- Pinned: a concrete regression, or in the cone of one. -/
  | c3
  /-- Witnessed: in a witness module, or in the cone of one. -/
  | c2
  /-- Consumed: some other declaration's kernel term uses it. -/
  | c1
  /-- Terminal: consumed by nothing, ledgered with a justification. -/
  | t
  /-- Uncovered: none of the above. The gate throws on these. -/
  | c0
  deriving BEq

/-- The class tag as it appears in the manifest (`"C4"` … `"C1"`, `"T"`,
`"C0"`). -/
def CovClass.tag : CovClass → String
  | .c4 => "C4"
  | .c3 => "C3"
  | .c2 => "C2"
  | .c1 => "C1"
  | .t => "T"
  | .c0 => "C0"

/-- Dependencies of `start`, restricted to `univ`, expanding through
non-universe names under the root (auto-generated companions, internal
auxiliaries) so `f.eq_1` and `_proof_1` links are not lost. -/
def expandedDeps (env : Environment) (root : Name) (univ : NameSet)
    (start : Name) : NameSet := Id.run do
  let mut seen : NameSet := {}
  let mut deps : NameSet := {}
  let mut work : List Name := [start]
  while h : work ≠ [] do
    let n := work.head h
    work := work.tail
    if seen.contains n then continue
    seen := seen.insert n
    let some ci := env.find? n | continue
    for d in ci.getUsedConstantsAsSet do
      -- Un-mangle for the root test only: unlike the universe, this walk
      -- must keep internal names (`_proof_1`, `eq_1`), so `auditRule` —
      -- which drops them — would sever exactly the links the docstring
      -- above promises to keep.
      if (privateToUserName d).getRoot == root && d != start then
        if univ.contains d then deps := deps.insert d
        else work := d :: work
  return deps

/-- Cone closure from a root set over the dependency edges. `depsOf` caches
the universe members' edges; anything outside it falls back to
`expandedDeps`. -/
def cone (env : Environment) (root : Name) (univ : NameSet)
    (depsOf : NameMap NameSet) (roots : List Name) : NameSet := Id.run do
  let mut seen : NameSet := {}
  let mut work := roots
  while h : work ≠ [] do
    let n := work.head h
    work := work.tail
    if seen.contains n then continue
    seen := seen.insert n
    for d in (depsOf.find? n).getD (expandedDeps env root univ n) do
      if !seen.contains d then work := d :: work
  return seen

/-- The coverage graph and classification over the declarations under
`root` — the one home for both phases (the gate at build time, the manifest
at runtime). `findings` holds the ledger-staleness defects as human-readable
strings; the gate turns the first into an error, the driver turns each into
a failure. A non-empty `findings` means the sets that ledger processing
builds (`bridged`, `terminal`) are not to be trusted for classification. -/
structure CoverageReport where
  /-- The universe: hand-written declarations under the root, mangled
  environment names. -/
  univ : NameSet
  /-- Count of names `auditRule` accepts that the auto-generated and
  projection exemptions removed from the universe. -/
  exempt : Nat
  /-- Each universe member's `expandedDeps`, cached. -/
  depsOf : NameMap NameSet
  /-- Universe members credited by some consumer outside their own name
  prefix. -/
  consumed : NameSet
  /-- Concrete-statement theorems: the roots of the pinned cone. -/
  pinRoots : List Name
  /-- The pinned cone: `pinRoots` and everything they depend on. -/
  pinned : NameSet
  /-- The witnessed cone: witness-module members and everything they depend
  on. -/
  witnessed : NameSet
  /-- Targets (and in-universe bridges) named in `bridgedLedger`. -/
  bridged : NameSet
  /-- Universe members ledgered in `terminalLedger`. -/
  terminal : NameSet
  /-- Ledger-staleness defects, in ledger order; empty on a healthy tree. -/
  findings : Array String

/-- Compute the coverage graph and classification for the declarations
under `root`. This is the whole computation `#coverage_report` used to do
inline, returned as data: the caller decides what a finding or an empty
universe means. -/
def computeCoverage (env : Environment) (root : Name) : CoverageReport := Id.run do
  let inPackage (n : Name) : Bool :=
    match moduleOf? env n with
    | some mod => mod.getRoot == root
    | none => true  -- compiled in the current file
  -- The universe: hand-written declarations under the namespace, by the
  -- same `auditRule` the axiom sweep and the manifest use — a mangled
  -- `_private.<Module>.<n>.<Name>` un-mangles before the root test, so a
  -- private declaration (the module system's default outside a
  -- `public section`) is classified rather than silently outside the
  -- universe. Sets and maps hold the mangled environment name; only the
  -- membership test un-mangles.
  let mut univ : NameSet := {}
  let mut exempt : Nat := 0
  for (n, _) in env.constants.toList do
    if auditRule root n then
      -- Projections are exempt with the other compiler output: a field is
      -- covered by any witness that constructs the structure, and the
      -- projection function itself is machinery.
      if isAutoGenerated n || env.isProjectionFn n then
        exempt := exempt + 1
      else univ := univ.insert n
  -- Consumers: every constant compiled in this package, internal included,
  -- credits its universe dependencies — except along its own name prefix.
  let mut consumed : NameSet := {}
  let mut depsOf : NameMap NameSet := {}
  for (n, _) in env.constants.toList do
    if inPackage n then
      let deps := expandedDeps env root univ n
      if univ.contains n then depsOf := depsOf.insert n deps
      for d in deps do
        unless d.isPrefixOf n do consumed := consumed.insert d
  -- Pinned: concrete regressions (closed statements) plus their cones.
  let mut pinRoots : List Name := []
  for n in univ do
    if let some (.thmInfo t) := env.find? n then
      if isConcreteStatement t.type then pinRoots := n :: pinRoots
  let pinned := cone env root univ depsOf pinRoots
  -- Witnessed: members of witness modules plus their cones.
  let mut witnessRoots : List Name := []
  for n in univ do
    match moduleOf? env n with
    | some mod =>
      if isWitnessModule root mod then witnessRoots := n :: witnessRoots
    | none => pure ()
  let witnessed := cone env root univ depsOf witnessRoots
  -- Ledgers, with staleness checks recorded as findings.
  -- Ledger entries for other namespaces are ignored: the ledgers are global,
  -- the report is per-root (the fixture reports over its own tiny namespace).
  let mut findings : Array String := #[]
  let mut bridged : NameSet := {}
  for (target, bridge) in bridgedLedger do
    unless target.getRoot == root do continue
    unless univ.contains target do
      findings := findings.push
        s!"bridged ledger names `{target}`, which is not in the universe"
      continue
    let some _ := env.find? bridge
      | findings := findings.push
          s!"bridged ledger cites missing bridge `{bridge}`"
        continue
    unless (expandedDeps env root univ bridge).contains target do
      findings := findings.push
        s!"`{bridge}` does not depend on `{target}`; the bridge entry is stale"
      continue
    bridged := bridged.insert target
    if univ.contains bridge then bridged := bridged.insert bridge
  let mut terminal : NameSet := {}
  for (n, why) in terminalLedger do
    unless n.getRoot == root do continue
    unless univ.contains n do
      findings := findings.push
        s!"terminal ledger names `{n}`, which is not in the universe"
      continue
    if consumed.contains n || witnessed.contains n || pinned.contains n then
      findings := findings.push
        s!"terminal entry `{n}` ({why}) is now covered — delete the entry"
      continue
    terminal := terminal.insert n
  return { univ, exempt, depsOf, consumed, pinRoots, pinned, witnessed,
           bridged, terminal, findings }

/-- Classify one universe member, strongest class first. -/
def CoverageReport.classOf (cov : CoverageReport) (n : Name) : CovClass :=
  if cov.bridged.contains n then .c4
  else if cov.pinned.contains n then .c3
  else if cov.witnessed.contains n then .c2
  else if cov.consumed.contains n then .c1
  else if cov.terminal.contains n then .t
  else .c0

/-- The class tally over the universe, uncovered names collected rather
than counted (the gate lists them in its error). -/
structure Tally where
  /-- Bridged count. -/
  c4 : Nat := 0
  /-- Pinned count. -/
  c3 : Nat := 0
  /-- Witnessed count. -/
  c2 : Nat := 0
  /-- Consumed count. -/
  c1 : Nat := 0
  /-- Terminal count. -/
  t : Nat := 0
  /-- The C0 names, in universe order. -/
  uncovered : Array Name := #[]

/-- Tally the universe by class. -/
def CoverageReport.tally (cov : CoverageReport) : Tally := Id.run do
  let mut acc : Tally := {}
  for n in cov.univ do
    match cov.classOf n with
    | .c4 => acc := { acc with c4 := acc.c4 + 1 }
    | .c3 => acc := { acc with c3 := acc.c3 + 1 }
    | .c2 => acc := { acc with c2 := acc.c2 + 1 }
    | .c1 => acc := { acc with c1 := acc.c1 + 1 }
    | .t => acc := { acc with t := acc.t + 1 }
    | .c0 => acc := { acc with uncovered := acc.uncovered.push n }
  return acc

end OverloadTest
