module

public meta import Lean.Elab.Command
public meta import OverloadTest.Coverage
import all Overload.Basic
import all Overload.Retry.Amplification
import all Overload.Retry.AttemptDist
import all Overload.Dynamics.Burst
import all Overload.Retry.Compose
import all Overload.Loop.Operator
import all Overload.Capacity.Conservation
import all Overload.Retry.Deadline
import all Overload.Capacity.Plateau
import all Overload.Loop.ClosedLoop
import all Overload.Dynamics.Calculus
import all Overload.Control.Breaker
import all Overload.Queueing.MM1
import all Overload.Queueing.Little
import all Overload.Queueing.Erlang
import all Overload.Stack.Coupling
import all Overload.Stack.Star
import all Overload.Retry.Composition
import all Overload.Stack.Scheme
import all Overload.Stack.CoupledStack
import all Overload.Stack.Tightness
import all Overload.Loop.Signature
import all Overload.Control.Priority
import all Overload.Control.Discipline
import all Overload.Capacity.Resources
import all Overload.Control.Observability
import all Overload.Verification.Suite
import all Overload.Loop.Universality
import all Overload.Loop.Hysteresis
import all Overload.Loop.Eligibility
import all Overload.Control.Autoscaling
import all Overload.Verification.Witnesses
import all Overload.Examples.SQS
import all Overload.Examples.Borg
import all Overload.Examples.Thrashing
import all Overload.Examples.Pipeline
import all Overload.Examples.Deficit
import all Overload.Examples.Mesh
import all Overload.Lint
import all Overload.AxiomAudit
public import OverloadTest.Coverage

/-!
# The coverage gate

Elaborating this file runs the coverage report over the whole library, so
`lake test` (which builds the test driver, which imports this) fails on any
uncovered declaration. The class tally lands in the build log next to the
axiom audit's count.

The `#coverage_report` elaborator is defined here rather than in
`OverloadTest/Coverage.lean` because the helpers it reads serve two phases:
the test driver executable calls them at runtime, so they cannot be `meta`,
and a command elaborator cannot call same-module non-`meta` code — the
`meta import` of `Coverage` is what lifts them across. The library
imports are `import all`, one per module, because the consumption
graph walks proof bodies (`getUsedConstantsAsSet`) and anything less
strips them: an exported-level import replaces a theorem with a
signature stub, and `import all` does not propagate through the
`Overload` aggregator — resolved either of those ways, every bridge
entry reads as stale. The list is hand-maintained like the two audit
roots; the `import-roots` stage checks all three.
-/

@[expose] public section

meta section

open Lean Elab Command in
/-- `#coverage_report Overload` fails elaboration unless every non-exempt
declaration under the namespace is bridged, witnessed, consumed, or ledgered
terminal. Prints the class tally so coverage is a build-log fact. See the
module docstring for the classes and the ledgers in `OverloadTest.Ledger`. -/
elab "#coverage_report " pfx:ident : command => do
  let env ← getEnv
  let root := pfx.getId
  let inPackage (n : Name) : Bool :=
    match OverloadTest.moduleOf? env n with
    | some mod => mod.getRoot == root
    | none => true  -- compiled in the current file
  -- The universe: hand-written declarations under the namespace, by the
  -- same `auditRule` the axiom sweep and the manifest use — a mangled
  -- `_private.<Module>.<n>.<Name>` un-mangles before the root test, so a
  -- private declaration (the module system's default outside a
  -- `public section`) is classified rather than silently outside the
  -- universe. Sets and maps hold the mangled environment name; only the
  -- membership test un-mangles.
  let mut univ : NameSet := {}
  let mut exempt : Nat := 0
  for (n, _) in env.constants.toList do
    if OverloadTest.auditRule root n then
      -- Projections are exempt with the other compiler output: a field is
      -- covered by any witness that constructs the structure, and the
      -- projection function itself is machinery.
      if OverloadTest.isAutoGenerated n || env.isProjectionFn n then
        exempt := exempt + 1
      else univ := univ.insert n
  if univ.isEmpty then
    throwError "#coverage_report: no declarations found under `{root}`"
  -- Dependencies of a constant, restricted to the universe, expanding
  -- through non-universe names under the root (auto-generated companions,
  -- internal auxiliaries) so `f.eq_1` and `_proof_1` links are not lost.
  let expandedDeps (start : Name) : NameSet := Id.run do
    let mut seen : NameSet := {}
    let mut deps : NameSet := {}
    let mut work : List Name := [start]
    while h : work ≠ [] do
      let n := work.head h
      work := work.tail
      if seen.contains n then continue
      seen := seen.insert n
      let some ci := env.find? n | continue
      for d in ci.getUsedConstantsAsSet do
        -- Un-mangle for the root test only: unlike the universe, this
        -- walk must keep internal names (`_proof_1`, `eq_1`), so
        -- `auditRule` — which drops them — would sever exactly the links
        -- the comment above promises to keep.
        if (privateToUserName d).getRoot == root && d != start then
          if univ.contains d then deps := deps.insert d
          else work := d :: work
    return deps
  -- Consumers: every constant compiled in this package, internal included,
  -- credits its universe dependencies — except along its own name prefix.
  let mut consumed : NameSet := {}
  let mut depsOf : NameMap NameSet := {}
  for (n, _) in env.constants.toList do
    if inPackage n then
      let deps := expandedDeps n
      if univ.contains n then depsOf := depsOf.insert n deps
      for d in deps do
        unless d.isPrefixOf n do consumed := consumed.insert d
  -- Cone closure from a root set over the dependency edges.
  let cone (roots : List Name) : NameSet := Id.run do
    let mut seen : NameSet := {}
    let mut work := roots
    while h : work ≠ [] do
      let n := work.head h
      work := work.tail
      if seen.contains n then continue
      seen := seen.insert n
      for d in (depsOf.find? n).getD (expandedDeps n) do
        if !seen.contains d then work := d :: work
    return seen
  -- Pinned: concrete regressions (closed statements) plus their cones.
  let mut pinRoots : List Name := []
  for n in univ do
    if let some (.thmInfo t) := env.find? n then
      if OverloadTest.isConcreteStatement t.type then pinRoots := n :: pinRoots
  let pinned := cone pinRoots
  -- Witnessed: members of witness modules plus their cones.
  let mut witnessRoots : List Name := []
  for n in univ do
    match OverloadTest.moduleOf? env n with
    | some mod =>
      if OverloadTest.isWitnessModule root mod then witnessRoots := n :: witnessRoots
    | none => pure ()
  let witnessed := cone witnessRoots
  -- Ledgers, with staleness checks.
  -- Ledger entries for other namespaces are ignored: the ledgers are global,
  -- the report is per-root (the fixture reports over its own tiny namespace).
  let mut bridged : NameSet := {}
  for (target, bridge) in OverloadTest.bridgedLedger do
    unless target.getRoot == root do continue
    unless univ.contains target do
      throwError "#coverage_report: bridged ledger names `{target}`, which is not in the universe"
    let some _ := env.find? bridge
      | throwError "#coverage_report: bridged ledger cites missing bridge `{bridge}`"
    unless (expandedDeps bridge).contains target do
      throwError
        "#coverage_report: `{bridge}` does not depend on `{target}`; the bridge entry is stale"
    bridged := bridged.insert target
    if univ.contains bridge then bridged := bridged.insert bridge
  let mut terminal : NameSet := {}
  for (n, why) in OverloadTest.terminalLedger do
    unless n.getRoot == root do continue
    unless univ.contains n do
      throwError "#coverage_report: terminal ledger names `{n}`, which is not in the universe"
    if consumed.contains n || witnessed.contains n || pinned.contains n then
      throwError "#coverage_report: terminal entry `{n}` ({why}) is now covered — delete the entry"
    terminal := terminal.insert n
  -- Tally, strongest class first.
  let mut c4 := 0; let mut c3 := 0; let mut c2 := 0; let mut c1 := 0; let mut t := 0
  let mut uncovered : Array Name := #[]
  for n in univ do
    if bridged.contains n then c4 := c4 + 1
    else if pinned.contains n then c3 := c3 + 1
    else if witnessed.contains n then c2 := c2 + 1
    else if consumed.contains n then c1 := c1 + 1
    else if terminal.contains n then t := t + 1
    else uncovered := uncovered.push n
  let total := univ.size
  let pct (k : Nat) : Nat := k * 100 / total
  unless uncovered.isEmpty do
    let names := uncovered.qsort (·.toString < ·.toString)
    throwError "#coverage_report: {uncovered.size} uncovered (C0) declaration(s) under \
      `{root}`:{indentD (MessageData.joinSep (names.toList.map (m!"{·}")) Format.line)}"
  logInfo m!"#coverage_report: {total} declarations under `{root}` — \
    C4 bridged {c4} ({pct c4}%), C3 pinned {c3} ({pct c3}%), \
    C2 witnessed {c2} ({pct c2}%), C1 consumed {c1} ({pct c1}%), \
    terminal {t} ({pct t}%), C0 uncovered 0 \
    (exempt auto-generated: {exempt})"

end

#coverage_report Overload
