import Lean
import Overload
import OverloadTest.Coverage
import OverloadTest.Gate

/-!
# The test driver

`lake exe overloadTest` is the runtime half of the test suite (the compile-time
half — axiom audit, coverage gate — runs while the libraries build). Stages:

1. **Manifest**: dump every hand-written declaration under `Overload` —
   qualified name, kind, module, pretty-printed elaborated type, value hash
   for definition kinds, docstring — to `.verify/manifest.json`. The types
   are elaborated, so `variable` binders are resolved by construction.
2. **Statement lock**: compare the manifest against the tracked
   `tests/statements.lock` and fail on removals, changes, *and additions*.
   `--update-lock` regenerates the lock instead; updating it is a deliberate,
   `git diff`-visible act, never a routine one.
   The comparator self-tests against doctored input on every run.
3. **Import roots**: every module under `Overload/` must be imported by both
   `Overload.lean` and `Overload/AxiomAudit.lean` (the audit sweep only sees
   what it imports). Read with `Lean.parseImports'`, not a regex.
4. **Negative fixtures**: the expected-failure suite from `tests/negative/`
   — each fixture must be rejected by the gate that owns it, with the
   expected message.
5. **Positive corpus**: `tests/positive/ScannerCorpus.lean` must elaborate
   and produce zero findings from the proof-token scanner.
6. **Prose checks**: the Python docs-sync suite (the proof-token scan over
   the library).

Statement types are printed in a bare context (no open namespaces), so the
output is deterministic for a pinned toolchain.
-/

open Lean System OverloadTest

/-- One manifest row. `valueHash?` is set for definition kinds only: theorem
proof bodies are deliberately free, definition bodies are part of the meaning
(`Coupling.Certificate` once changed body with no header drift reported). -/
structure Entry where
  name : String
  kind : String
  module : String
  type : String
  valueHash? : Option String
  doc? : Option String

def Entry.toJson (e : Entry) : Json :=
  Json.mkObj <|
    [("name", Json.str e.name), ("kind", Json.str e.kind),
     ("module", Json.str e.module), ("type", Json.str e.type)]
    ++ (match e.valueHash? with | some h => [("valueHash", Json.str h)] | none => [])
    ++ (match e.doc? with | some d => [("doc", Json.str d)] | none => [])

/-- The lock block for one declaration: a `#### ` header line, the printed
type indented beneath it, and for definition kinds a value-hash line. -/
def Entry.lockBlock (e : Entry) : String :=
  let typeLines := (e.type.splitOn "\n").map ("  " ++ ·)
  let valueLine := match e.valueHash? with
    | some h => ["  value-hash " ++ h]
    | none => []
  String.intercalate "\n" ([s!"#### {e.name} : {e.kind}"] ++ typeLines ++ valueLine)

def kindOf (env : Environment) (n : Name) (ci : ConstantInfo) : String :=
  match ci with
  | .thmInfo _ => "theorem"
  | .defnInfo _ => "def"
  | .opaqueInfo _ => "opaque"
  | .axiomInfo _ => "axiom"
  | .quotInfo _ => "quot"
  | .inductInfo _ => if isStructure env n then "structure" else "inductive"
  | .ctorInfo _ => "ctor"
  | .recInfo _ => "recursor"

def hex (h : UInt64) : String :=
  String.ofList (Nat.toDigits 16 h.toNat)

/-- The audit-count rule of `#axiom_budget_all`: non-internal declarations
under the root, printed alongside the runtime stages. -/
def auditCount (env : Environment) (root : Name) : Nat := Id.run do
  let mut k := 0
  for (n, _) in env.constants.toList do
    if n.getRoot == root && !n.isInternal then k := k + 1
  return k

/-- Collect and pretty-print the manifest rows for the hand-written
declarations under `root`, sorted by name. -/
def manifestEntries (root : Name) : CoreM (Array Entry) := do
  let env ← getEnv
  let mut names : Array Name := #[]
  for (n, _) in env.constants.toList do
    if n.getRoot == root && !n.isInternal
        && !isAutoGenerated n && !env.isProjectionFn n then
      names := names.push n
  names := names.qsort (·.toString < ·.toString)
  let mut entries : Array Entry := #[]
  for n in names do
    let some ci := env.find? n | continue
    let type ← Meta.MetaM.run' do
      return (← Meta.ppExpr ci.type).pretty (width := 100)
    let valueHash? ← match ci with
      | .defnInfo d => do
        let v ← Meta.MetaM.run' do
          return (← Meta.ppExpr d.value).pretty (width := 100)
        pure (some (hex v.hash))
      | _ => pure none
    let doc? ← findDocString? env n
    let module := (moduleOf? env n).map (·.toString) |>.getD "<current>"
    entries := entries.push
      { name := n.toString, kind := kindOf env n ci, module, type, valueHash?, doc? }
  return entries

/-- Split a lock file into `name ↦ block` (blocks begin at `#### `). -/
def parseLock (text : String) : Std.HashMap String String := Id.run do
  let mut m : Std.HashMap String String := {}
  let mut name : Option String := none
  let mut block : Array String := #[]
  for line in text.splitOn "\n" do
    if line.startsWith "#### " then
      if let some k := name then m := m.insert k (String.intercalate "\n" block.toList)
      name := some line
      block := #[line]
    else if name.isSome && !line.isEmpty then
      block := block.push line
  if let some k := name then m := m.insert k (String.intercalate "\n" block.toList)
  return m

/-- Compare current entries against a lock. Returns human-readable findings;
empty means the statements are unchanged. -/
def lockDiff (lock : Std.HashMap String String) (entries : Array Entry) :
    Array String := Id.run do
  let mut findings : Array String := #[]
  let mut current : Std.HashMap String String := {}
  for e in entries do
    let block := e.lockBlock
    let header := (block.splitOn "\n").head!
    current := current.insert header block
    match lock.get? header with
    | none => findings := findings.push s!"added: {e.name} ({e.kind})"
    | some old =>
      if old != block then
        findings := findings.push s!"changed: {e.name} ({e.kind})"
  for (header, _) in lock.toList do
    unless current.contains header do
      findings := findings.push s!"removed: {header.drop 5}"
  return findings.qsort (· < ·)

/-- The comparator must actually see removals, changes, and additions before
it is trusted on the real tree: run it against doctored input every time. -/
def selfTestLock : IO Unit := do
  let a : Entry := { name := "T.a", kind := "theorem", module := "T", type := "1 = 1", valueHash? := none, doc? := none }
  let b : Entry := { name := "T.b", kind := "def", module := "T", type := "Nat", valueHash? := some "ff", doc? := none }
  let lock := parseLock (a.lockBlock ++ "\n" ++ b.lockBlock ++ "\n")
  unless (lockDiff lock #[a, b]).isEmpty do
    throw <| IO.userError "lock self-test: clean compare reported findings"
  let d1 := lockDiff lock #[a]
  unless d1.size == 1 && (d1[0]!.startsWith "removed: T.b") do
    throw <| IO.userError s!"lock self-test: removal not reported: {d1}"
  let d2 := lockDiff lock #[a, { b with type := "Int" }]
  unless d2.size == 1 && (d2[0]!.startsWith "changed: T.b") do
    throw <| IO.userError s!"lock self-test: type change not reported: {d2}"
  let d3 := lockDiff lock #[a, { b with valueHash? := some "00" }]
  unless d3.size == 1 && (d3[0]!.startsWith "changed: T.b") do
    throw <| IO.userError s!"lock self-test: value change not reported: {d3}"
  let d4 := lockDiff lock #[a, b, { a with name := "T.c" }]
  unless d4.size == 1 && (d4[0]!.startsWith "added: T.c") do
    throw <| IO.userError s!"lock self-test: addition not reported: {d4}"

/-- Modules under `Overload/`, from the filesystem. -/
def sourceModules : IO (Array Name) := do
  let files ← FilePath.walkDir "Overload"
  let mut mods : Array Name := #[]
  for f in files do
    if f.extension == some "lean" then
      let parts := f.withExtension "" |>.components
      mods := mods.push (parts.foldl (init := Name.anonymous) .str)
  return mods

def importsOf (file : FilePath) : IO (Array Name) := do
  let header ← parseImports' (← IO.FS.readFile file) file.toString
  return header.imports.map (·.module)

/-- Run a process, returning exit code and combined output. -/
def run (cmd : String) (args : Array String) : IO (UInt32 × String) := do
  let out ← IO.Process.output { cmd, args }
  return (out.exitCode, out.stdout ++ out.stderr)

structure Failure where
  stage : String
  detail : String

def negativeFixtures : List (String × String) :=
  [("SorryFixture.lean", "depends on sorryAx"),
   ("NativeDecideFixture.lean", "._native.native_decide.ax"),
   ("OmittedTokenFixture.lean", "carries the omitted-result token `exitTime`"),
   ("CoverageFixture.lean", "uncovered (C0)")]

def scannerFixtures : List String :=
  ["ExampleSorryFixture.lean", "StringSorryFixture.lean",
   "SorryAxFixture.lean", "StopFixture.lean", "NativePlusFixture.lean"]

unsafe def main (args : List String) : IO UInt32 := do
  let update := args.contains "--update-lock"
  unless (← FilePath.pathExists "Overload.lean") do
    throw <| IO.userError "run from the repo root (Overload.lean not found)"
  initSearchPath (← findSysroot)
  enableInitializersExecution
  let env ← importModules #[{module := `Overload}, {module := `Overload.AxiomAudit}]
    {} (trustLevel := 1024) (loadExts := true)
  let count := auditCount env `Overload
  IO.println s!"overloadTest: environment loaded, audit-rule count {count}"
  let mut failures : Array Failure := #[]

  -- [1] manifest
  let ctx : Core.Context := { fileName := "<overloadTest>", fileMap := default }
  let entries ← Prod.fst <$> (manifestEntries `Overload).toIO ctx { env }
  IO.FS.createDirAll ".verify"
  IO.FS.writeFile ".verify/manifest.json"
    ((Json.arr (entries.map Entry.toJson)).pretty.push '\n')
  IO.println s!"manifest: {entries.size} declarations -> .verify/manifest.json"

  -- [2] statement lock
  selfTestLock
  let lockFile : FilePath := "tests" / "statements.lock"
  let lockText := String.intercalate "\n\n" (entries.map Entry.lockBlock).toList
  if update then
    IO.FS.writeFile lockFile
      ("-- Statement lock: elaborated types (and definition value hashes) of\n\
        -- every hand-written declaration under `Overload`, printed by\n\
        -- `lake exe overloadTest --update-lock`. Proof bodies of theorems are\n\
        -- deliberately not frozen. A diff in this file is a deliberate\n\
        -- statement-level change, never a routine one.\n\n"
        ++ lockText ++ "\n")
    IO.println s!"lock: wrote {entries.size} blocks to {lockFile}"
  else if (← lockFile.pathExists) then
    let diffs := lockDiff (parseLock (← IO.FS.readFile lockFile)) entries
    if diffs.isEmpty then
      IO.println s!"lock: {entries.size} statements match {lockFile} (self-test ok)"
    else
      for d in diffs do
        failures := failures.push ⟨"lock", d⟩
  else
    failures := failures.push ⟨"lock", s!"{lockFile} missing; run with --update-lock"⟩

  -- [3] import roots
  let mods ← sourceModules
  let rootImports ← importsOf "Overload.lean"
  let auditImports ← importsOf ("Overload" / "AxiomAudit.lean")
  for m in mods do
    unless rootImports.contains m do
      failures := failures.push ⟨"import-roots", s!"{m} not imported by Overload.lean"⟩
    unless m == `Overload.AxiomAudit || auditImports.contains m do
      failures := failures.push ⟨"import-roots", s!"{m} not imported by Overload/AxiomAudit.lean"⟩
  IO.println s!"import-roots: {mods.size} modules checked against both roots"

  -- [4] negative fixtures
  for (file, expected) in negativeFixtures do
    let (code, out) ← run "lean" #[s!"tests/negative/{file}"]
    if code == 0 then
      failures := failures.push ⟨"negative", s!"{file} elaborated; it must be rejected"⟩
    else if (out.splitOn expected).length > 1 then
      IO.println s!"negative: {file} rejected as expected"
    else
      failures := failures.push ⟨"negative", s!"{file} failed without the expected message ({expected}):\n{out}"⟩
  for file in scannerFixtures do
    let (code, out) ← run "python3"
      #["scripts/checks.py", "--scan", s!"tests/negative/{file}"]
    if code == 0 then
      failures := failures.push ⟨"negative", s!"{file} passed the proof-token scan; it must be rejected"⟩
    else
      IO.println s!"negative: {file} rejected by proof-tokens: {out.trimAscii.toString}"

  -- [5] positive corpus
  let corpus := "tests/positive/ScannerCorpus.lean"
  let (code, out) ← run "python3" #["scripts/checks.py", "--scan", corpus]
  if code != 0 then
    failures := failures.push ⟨"positive", s!"scanner false-positive on {corpus}:\n{out}"⟩
  let (code2, out2) ← run "lean" #[corpus]
  if code2 != 0 then
    failures := failures.push ⟨"positive", s!"{corpus} does not elaborate:\n{out2}"⟩
  if code == 0 && code2 == 0 then
    IO.println s!"positive: {corpus} elaborates, zero scanner findings"

  -- [6] prose checks
  let (code, out) ← run "python3" #["scripts/checks.py", "."]
  IO.print out
  if code != 0 then
    failures := failures.push ⟨"prose", "checks.py failed (see output above)"⟩

  if failures.isEmpty then
    IO.println "overloadTest: all runtime stages green"
    return 0
  else
    for f in failures do
      IO.eprintln s!"FAIL [{f.stage}] {f.detail}"
    return 1
