import OverloadTest.Gate

/-! Expected-failure fixture for the coverage gate: a general theorem that is
consumed by nothing, witnessed by nothing, and ledgered nowhere must be
reported as C0 and fail elaboration. If this file elaborates, the gate is
open. -/

namespace CovFixture

/-- A perfectly true, perfectly unverified-beyond-itself theorem. -/
theorem unusedGeneral (n : Nat) : n = n := rfl

/-- A concrete regression: classified C3, so it must NOT appear in the C0
list below — the failure message names `unusedGeneral` and the four sneaky
prefix-named theorems, never this one. -/
theorem pinnedConcrete : 1 + 1 = 2 := rfl

/-! Hand-written names carrying compiler-auxiliary prefixes. The exemption
in `isAutoGenerated` accepts those prefixes only with a digit suffix
(`eq_1`, `match_1_1`, `proof_2`, `congr_1`), so all four must stay in the
universe and be reported C0 — a bare-prefix test swallowed
`ClosedLoop.eq_ge_of_over` out of the universe, the manifest, and the lock
(found 2026-07-26; same defect class as the `instrument_blind` swallow). -/

theorem eq_sneaky (n : Nat) : n = n := rfl

theorem congr_sneaky (n : Nat) : n = n := rfl

theorem match_sneaky (n : Nat) : n = n := rfl

theorem proof_sneaky (n : Nat) : n = n := rfl

end CovFixture

#coverage_report CovFixture
